name: Moon Wolf
favicon: null
layout_spectrum: 0.0634349447209388
typography_spectrum: 0.19118623272515833
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030406'
    - '#aaaeb1'
    - '#696a64'
    - '#d9dad5'
    - '#b24917'
  brandStrength: 0.3125
  lightness: 0.716524644754827
  saturation: 0.07625461858697236
  rhythmicContrast: 0.9946396960876882
purpose: []
