name: Moon Wolf
favicon: null
layout_spectrum: 0.97348
typography_spectrum: 0.21103
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030406'
    - '#aaaeb1'
    - '#696a64'
    - '#d9dad5'
    - '#b24917'
  brandStrength: 0.8125
  lightness: 0.5
  saturation: 0.875
  rhythmicContrast: 0.5
purpose: []
